services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ms-productos:
    build:
      context: ./ms-productos
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API_KEY: app-secret
      SERVER_PORT: 8081
    depends_on:
      - postgres

  ms-inventario:
    build:
      context: ./ms-inventario
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      API_KEY: app-secret
      PRODUCTOS_SERVICE_URL: http://ms-productos:8081
      server.port: 8080
    depends_on:
      - postgres
      - ms-productos

volumes:
  pgdata:
